# Site settings
title: The Unheard Silence
header-img: img/home-bg.jpg
email: singhhunny08@gmail.com
copyright_name: TheUnheardSilence
description: "The Unheard Silence"
baseurl: "" #base url is for when the site is not at the root but at some subdirectory.
disqus_url: shikherverma.com # disque comments are broken if you send http:// along with url
github_username:  theunheardsilence
facebook_username: gurkirat.singh.169

# used to estimate reading time
wpm: 150

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate
paginate: 5
paginate_path: blog/page:num

# gem dependencies
gems: [jekyll-paginate, jekyll-feed, jekyll-gist]
